package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Base.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//



/**
 * Base class. Responsible for creating destroying and managing Bases.
 */
public class Base extends Building {
	
//Constructors:------------------------------------------	
	public Base () {
		id = "bas" + nextId;
		nextId++;
	}
	
	public Base (String _id, Asteroid _asteroid) {
		id = _id;
		asteroid = _asteroid;
	}
	
//Get/Set----------------------------------------------
	
//Inherited:------------------------------------------------
	
	@Override
	public String genUIString() {
		return "Base id: " + id + "\n" 
				+ "asteroid: " + asteroid.getId();
	}

	@Override
	public String genSaveString() {		
		return "id: " + id + "\n"
				+ "asteroid: " + Tools.id(asteroid);
	}

	@Override
	public void getNotifiedAboutSunflare() {
		//Do nothing
	}

	/**
	 * method called, when placed on asteroid
	 */
	public void onPlace() {
		owner.gameWon();
	}

	/**
	 * function for destroying the base
	 */
	public void destroy() {
		asteroid.removeBuilding(this);
	}

	@Override
	public void onTurn() {
		//Do nothing
	}
	
}
