package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Base.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//



/**
 * Base class. Responsible for creating destroying and managing Bases.
 */
public class Base extends Building {
	
//Constructors:------------------------------------------	
	public Base () {
	}
	
//Get/Set----------------------------------------------
	
//Inherited:------------------------------------------------
	
	@Override
	public String genUIString() {
		return "Base id: " + id + "\n" 
				+ "asteroid: " + asteroid.getId() + "\n";
	}

	@Override
	public String genSaveString() {		
		return "Base:\n"
				+ "id: " + id + "\n"
				+ "asteroid: " + Tools.id(asteroid) + "\n"
				+ ";\n";
	}

	@Override
	public void getNotifiedAboutSunflare() {
		//Do nothing
	}

	/**
	 * method called, when placed on asteroid
	 */
	public void onPlace() {
		owner.gameWon();
	}

	/**
	 * function for destroying the base
	 */
	public void destroy() {
		asteroid.removeBuilding(this);
	}
}
