package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Base.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Base extends Building {
	
	public Base () {
	}
	
	@Override
	public void onPlace(Asteroid a) {
		// TODO Auto-generated method stub
		owner.gameWon();
		
	}

	@Override
	public void destroy() {
		// TODO Auto-generated method stub
		
	}
}
