package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Building.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public abstract class Building {
	protected Asteroid asteroid;
	protected Game owner;
	protected Main main;
	
	public Asteroid getAsteroid() { return asteroid; }
	public void setAsteroid(Asteroid a) { asteroid = a; }
	
	public Game getGame() { return owner; }
	public void setGame(Game g) { owner = g; }
	
	public void setMain(Main m) { main = m; }
	
	public Building() {
	}
	
	public abstract void onPlace(Asteroid a); 
	
	public abstract void destroy(); 
}
