package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Building.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//


/**
 * Building abstract base class.
 */
public abstract class Building extends Printable implements Controllable, ReactsToSunFlare {
	protected Asteroid asteroid;	//Built on this Asteroid.
	protected Game owner;

//Constructors:----------------------------------------------------

	public Building() {
	}
	
//Get/Set---------------------------------------------------------	

	public Asteroid getAsteroid() {
		return asteroid;
	}


	public void setAsteroid(Asteroid asteroid) {
		this.asteroid = asteroid;
	}
	
	public Game getOwner() {
		return owner;
	}

	public void setOwner(Game owner) {
		this.owner = owner;
	}	

//Methods:---------------------------------------------------------
	
	/**
	 * Called after building got placed on asteroid.
	 */
	public abstract void onPlace(); 
	
	/**
	 * Destroys building.
	 */
	public abstract void destroy(); 
}
