package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Coal.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//

public class Coal extends Material {

//Constructors:----------------------------------------------------------------

	/**
	 * Constructor for Coal.
	 */
	Coal(String id){
		super(false, "Coal", false, 0);
		this.id = id;
	}
	
	/**
	 * Constructor for Coal without parameters.
	 */
	Coal(){
		super(false, "Coal", true , 0);
        this.id = "coa" + String.valueOf(nextId);
        nextId++;
	}
}
