package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Coal.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//

public class Coal extends Material {

//Constructors:----------------------------------------------------------------

	Coal(){
		super(false, "Coal", false, 0);
	}
}
