package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Controllable.java
//  @ Date : 17/03/2021
//  @ Author : KMark
//
//
public interface Controllable {
	
	/**
	 * Abstract function that gets called at the start of turn when the given controllable does its job
	 */
	public void onTurn();
}
