package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Controllable.java
//  @ Date : 17/03/2021
//  @ Author : Karpati Mark
//
//




public interface Controllable {
	public void onTurn();
	
}
