package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Destroyable.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Destroyable {
}
