	package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Entity.java
//  @ Date : 17/03/2021
//  @ Author : TAdam
//
//


/**
 * 
 * @author TAdam
 * Entity abstract base class.
 */

public abstract class Entity extends Printable implements ReactsToSunFlare, Moving {
	protected Game owner;
	protected Asteroid asteroid;
	/**
	 * Constructor without parameters.
	 */
	public Entity() {
		
	}
	/**
	 * Constructor with parameters.
	 * @param _id: String: The id of the Entity object.
	 * @param _owner: Game: The owner of this Entity object.
	 * @param _asteroid: Asteroid: The asteroid of the entity.
	 */
	public Entity(String _id, Game _owner, Asteroid _asteroid) {
		id = _id;
		owner = _owner;
		asteroid = _asteroid;
	}
	/**
	 * Getter for the id.
	 * @return id: String
	 */
	public String getId() {
		return id;
	}
	/**
	 * Setter for the id.
	 * @param newid: String
	 */
	public void setId(String newid) {
		id = newid;
	}
	/**
	 * Getter for the owner.
	 * @return owner: Game
	 */
	public Game getOwner() {
		return owner;
	}
	/**
	 * Setter for the owner.
	 * @param newowner: Game
	 */
	public void setOwner(Game newowner) {
		owner = newowner;
	}
	/**
	 * Getter for the asteroid.
	 * @return asteroid: Asteroid
	 */
	public Asteroid getAsteroid() {
		return asteroid;
	}
	/**
	 * Setter for the asteroid.
	 * @param newasteroid: Asteroid
	 */
	public void setAsteroid(Asteroid newasteroid) {
		asteroid = newasteroid;
	}
	
	/**
	 * The Entity reacts to sunflare.
	 * If the asteroid of the entity isn't hollow it dies.
	 */
	public void getNotifiedAboutSunflare() {
		if(this.asteroid.isHollow() == false && this.asteroid.getRockThickness() == 0) {
			this.die();
		}
	}
		
	/**
	 * Entity dies.
	 * Removes the entity from the current asteroid.
	 */
	public abstract void die();
	/**
	 * The asteroid of the entity exploded.
	 */
	public abstract void asteroidExploded();
	/**
	 * Printing method inherited from Printable.
	 */
	public abstract String genUIString();
	/**
	 * Serialization inherited from Printable.
	 */
	public abstract String genSaveString();
}
