package main;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Game.java
//  @ Date : 17/03/2021
//  @ Author : Simon Zoltán
//
//




public class Game {
	private List<Controllable> controllables;
	private List<Planet> planets;		//???
	private List<Settler> settlers;
	
	public Game() {
		controllables = new ArrayList<>();
		planets = new ArrayList<>();
		settlers = new ArrayList<>();
	}
	
	public void destroyMe(Controllable toDestroy) {
		controllables.remove(toDestroy);
	}
	
	
	public void killMe(Settler toKill) {
		settlers.remove(toKill);
	}
	
	public void notifyAllAboutSunFlare() {
		for (Planet planet : planets) {
			planet.getNotifiedAboutSunflare();
		}
	}
	
	public void gameWon() {
		System.out.println("Game won!");
	}
	
	public void addControllable(Controllable c) {
		controllables.add(c);
	}	
	
	public void addSettler(Settler s) {
		settlers.add(s);
	}
}
