package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Ice.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//




public class Ice extends Material {
	
	/**
	 * Constructor for Ice.
	 */
	Ice(){
		super(false, "Ice", true);
	}
	
	/**
	 * Evaporate the ice from the asteroid.
	 */
	public void exposedAndCloseToSun(Asteroid a) {
		this.main.log(false, this.name, this.getClass().getName(), "exposedAndCloseToSun(" + a.getName() + ":" + (a.getClass().getName()));
		a.evaporateMaterial();
		this.main.log(true, "void", "void", "");
	}
}
