package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Ice.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//

public class Ice extends Material {

//Constructors:----------------------------------------------------------------

	/**
	 * Constructor for Ice.
	 */
	Ice(){
		super(false, "Ice", true , 0);
	}

//Own methods:----------------------------------------------------------------------------

    /**
     * If the Material exposed to the sun then this function 
     * evaporate the ice from the asteroid.
     */
	public void exposedAndCloseToSun(Asteroid a) {
		super.exposedAndCloseToSun(a);
		a.evaporateMaterial();
	}
}
