package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Iron.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//

public class Iron extends Material {

//Constructors:----------------------------------------------------------------

	/**
	 * Constructor for Iron.
	 */
	Iron(String id){
		super(false, "Iron", false, 0);
		this.id = id;
	}
	
	/**
	 * Constructor for Iron without parameters.
	 */
	Iron(){
		super(false, "Iron", true , 0);
        this.id = "Iron" + String.valueOf(nextId);
        nextId++;
	}
}
