package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Material.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//

public abstract class Material extends Printable{
	protected boolean isRadio;
	protected String name;
	protected boolean canEvaporate;
	protected int exposedCounter;
	
//Constructors:----------------------------------------------------------------
	
	/**
	 * Constructor for the Material which sets all parameters at once.	
	 * @param boolean: isRadio
	 * @param String: name
	 * @param boolean: canEvaporate
	 */
	Material(boolean isRadio, String name, boolean canEvaporate, int exposedCounter){
		this.isRadio = isRadio;
		this.name = name;
		this.canEvaporate = canEvaporate;
		this.exposedCounter = exposedCounter;
	}
	
	/**
	 * Constructor for the Material which use other Materials parameters.
	 * @param Material: m
	 */
	Material(Material m)
	{
		this.id = m.id;
		this.isRadio = m.isRadio();
		this.name = m.getName();
		this.canEvaporate = m.isCanEvaporate();
	}
	
//Get/Set-----------------------------------------------------------------

	public boolean isRadio() {
		return isRadio;
	}

	public void setRadio(boolean isRadio) {
		this.isRadio = isRadio;
	}

	public boolean isCanEvaporate() {
		return canEvaporate;
	}

	public void setCanEvaporate(boolean canEvaporate) {
		this.canEvaporate = canEvaporate;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {		
		this.name = name;
	}
	
	public int getExposedCounter() {
		return exposedCounter;
	}

	public void setExposedCounter(int exposedCounter) {		
		this.exposedCounter = exposedCounter;
	}
	
//Inherited:-----------------------------------------------------------------------------

	//Printable
	
    /**
     * Creates a string with this class' all important data.
     *
     * @return String: containing all the important information for the user
     */
	@Override
	public String genUIString() {
		return "Material id: " + id + "\n"
				+ "Name: " + name + "\n";
	}
	
//Own methods:----------------------------------------------------------------------------
	 
    /**
     * If the Material exposed to the sun then this function
     * increase the exposedCounter.
     */
	public void exposedAndCloseToSun(Asteroid a) {
		if(exposedCounter>=3) return;
		this.exposedCounter++;
	}
	
    /**
     * Creates a string storing the most important datas of this class.
     * 
     * @return String: containing all the important information
     */
	@Override
	public String genSaveString() {
		 String returnValue ="id: " + this.id + "\n" +
	                "isRadio:" + Tools.bool(this.isRadio) + "\n" +
	                "name: " + this.name + "\n" +
	                "canEvaporate: " + Tools.bool(this.canEvaporate) + "\n" +
	                "exposedCounter: " + this.exposedCounter + "\n";
		return returnValue;
	}
}
