package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Planet.java
//  @ Date : 17/03/2021
//  @ Author : Simon Zoltán
//
//



/**
 * Abstract parent class of different space objects in game.
 * @author simon
 *
 */
public abstract class Planet {
	protected Main main; //Logger
	protected String name;
	
	protected Game owner;
	
	/**
	 * Called when sun flare occurs.
	 * Could be overwritten in derived classes. 
	 */
	public void getNotifiedAboutSunflare() {
	}

	public Game getOwner() {
		return owner;
	}

	public void setOwner(Game owner) {
		this.owner = owner;
	}
	
	//Logger:-------------------------------------
	public void setMain(Main m) {
		main = m;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	

}
