package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Robot.java
//  @ Date : 17/03/2021
//  @ Author : Tadam
//
//



/**
 * Robot class, extends Entity
 * @author Tadam
 *
 */
public class Robot extends Entity implements Controllable {
	/**
	 * Default constructor without parameters.
	 */
	public Robot() {
		super();
	}
	/**
	 * Constructor with parameters.
	 * @param asteroid: Asteroid: The Asteroid which this Robot is standing on.
	 * @param owner: The game which this Settler belongs to.
	 */
	public Robot(Asteroid asteroid, Game owner) {
		super(asteroid, owner);
	}
	/**
	 * The robot decides what to do.
	 */
	@Override
	public void onTurn() {
		// TODO Auto-generated method stub
		
	}
	/**
	 * Robot dies.
	 */
	public void die() {
		super.die();
		owner.destroyMe(this);
	}
	
	public void asteroidExploded() {
		// TODO Auto-generated method stub
		
	}
	
}
