package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Settler.java
//  @ Date : 17/03/2021
//  @ Author : Tadam
//
//



/**
 * Settler class, extends Entity
 * @author Tadam
 *
 */
public class Settler extends Entity {
	private Inventory inventory;
	private Inventory BASE_RECIPE;
	private Inventory ROBOT_RECIPE;
	private Inventory STARGATE_RECIPE;
	
	/**
	 * Default Constructor without parameters.
	 */
	public Settler() {
		super();
		inventory = new Inventory();
		BASE_RECIPE = new Inventory();
		ROBOT_RECIPE = new Inventory();
		STARGATE_RECIPE = new Inventory();
	}
	/**
	 * Constructor with parameters.
	 * @param asteroid: Asteroid: The Asteroid which this Settler is standing on.
	 * @param owner: Game: The game which this Settler belongs to.
	 */
	public Settler(Asteroid asteroid, Game owner) {
		super(asteroid, owner);
		inventory = new Inventory();
		BASE_RECIPE = new Inventory();
		ROBOT_RECIPE = new Inventory();
		STARGATE_RECIPE = new Inventory();
	}
	/**
	 * The setter of the inventory.
	 * @param i: Inventory: The inventory of the settler.
	 */
	public void setInventory(Inventory i) {
		inventory = i;
	}
	/**
	 * The getter of the settler's inventory
	 * @return inventory: Inventory
	 */
	public Inventory getInventory() {
		return inventory;
	}
	/**
	 * The setter of the STARGATE_RECIPE
	 * @param i: Inventory: Contains the required materials 
	 */
	public void setSTARGATE_RECIPE(Inventory i) {
		STARGATE_RECIPE = i;
	}
	/**
	 * The setter of the ROBOT_RECIPE
	 * @param i: Inventory: Contains the required materials 
	 */
	public void setROBOT_RECIPE(Inventory i) {
		ROBOT_RECIPE = i;
	}
	/**
	 * The setter of the BASE_RECIPE
	 * @param i: Inventory: Contains the required materials 
	 */
	public void setBASE_RECIPE(Inventory i) {
		BASE_RECIPE = i;
	}
	/**
	 * This settler mines on his asteroid.
	 */
	public void mine() {
		main.log(false, name, this.getClass().getName(), "mine()");
		Material m = this.asteroid.removeMaterial();
		inventory.addInventory(m);
		main.log(true, "void", "void", "");
	}
	/**
	 * This settler builds a Stargate.
	 */
	public void buildStarGate() {
		main.log(false, name, this.getClass().getName(), "buildStarGate()");
		Inventory remainder = STARGATE_RECIPE.subSet(inventory);
		if(remainder.getMaterials().size() == 0) {
			this.setInventory(STARGATE_RECIPE.subtraction(inventory));
			StarGate s1 = new StarGate();
			s1.setName("stargate");
			StarGate s2 = new StarGate();
			s2.setName("neighbour");
			s1.setNeighbour(s2);
			s2.setNeighbour(s1);
			inventory.addStarGate(s1);
			inventory.addStarGate(s2);
		}
		main.log(true, "void", "void", "");
	}
	/**
	 * This settler builds a Robot.
	 */
	public void buildRobot() {
		main.log(false, name, this.getClass().getName(), "buildRobot()");
		Inventory remainder = ROBOT_RECIPE.subSet(inventory);
		if(remainder.getMaterials().size() == 0) {
			this.setInventory(ROBOT_RECIPE.subtraction(inventory));
			Robot robot = new Robot();
			robot.setName("robot");
			robot.setAsteroid(asteroid);
			asteroid.addEntity(robot);
			owner.addRobot(robot);
		}
		main.log(true, "void", "void", "");
	}
	/**
	 * This settler builds a Base.
	 */
	public void buildBase() {
		main.log(false, name, this.getClass().getName(), "buildBase()");
		main.log(true, "void", "void", "");
	}
	/**
	 * This settler tries to drop a material.
	 * If he can drop it, he removes it from his inventory.
	 * @param m: Material: The material which the settler wants to drop.
	 */
	public void dropMaterial(Material m) {
		main.log(false, name, this.getClass().getName(), "dropMaterial("+m.getName()+")");
		boolean b = asteroid.addMaterial(m);
		if(b == true) {
			this.inventory.removeInventory(m);
		}
		main.log(true, "void", "void", "");
	}
	/**
	 * The settler places a Stargate on the current asteroid.
	 */
	public void placeStarGate() {
		main.log(false, name, this.getClass().getName(), "placeStarGate()");
		StarGate sg = inventory.removeStarGate();
		asteroid.addBuilding(sg);
		sg.onPlace(asteroid);
	}
	/**
	 * The settler dies.
	 */
	public void die() {
		main.log(false, name, this.getClass().getName(), "die()");
		super.die();
		owner.killMe(this);
		main.log(true, "void", "void", "");
	}
	/**
	 * The asteroid of this settler has been exploded.
	 * The settler dies.
	 */
	public void asteroidExploded() {
		main.log(false, name, this.getClass().getName(), "asteroidExploded()");
		this.die();
		main.log(true, "void", "void", "");
	}
}
