package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : StarGate.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class StarGate extends Building {
	private boolean works;
	private StarGate neighbour;
	
	public boolean getWorks() { return works; }
	public void setWorks(boolean b) { works = b; }
	
	public StarGate getNeighbour() { return neighbour; }
	public void setNeighbour(StarGate sg) { neighbour = sg; }
	
	public StarGate() {
		works = false;
	}
	
	public void onPlace(Asteroid a) {
		main.log(false, "stargate", "StarGate", "onPlace(asteroid:Asteroid");
		
		if (neighbour == null)
			return;
		
		if (neighbour.getWorks() == false)
			return;
		
		asteroid.addNeighbour(getNeighbourAsteroid());
		getNeighbourAsteroid().addNeighbour(asteroid);
		
		main.log(true, "void", "Void", "");
	}
	
	public void destroy() {
		main.log(false, "stargate", "StarGate", "destroy()");
		
		neighbour.setWorks(false);
		
		getNeighbourAsteroid().removeNeighbour(asteroid);
		asteroid.removeNeighbour(getNeighbourAsteroid());
		
		neighbour.setNeighbour(null);
		
		main.log(true, "void", "Void", "");
	}
	
	public Asteroid getNeighbourAsteroid() {
		main.log(false, "stargate", "StarGate", "getNeighbourAsteroid()");
		
		main.log(true, "neighbour", "Asteroid", "");
		
		return neighbour.getAsteroid();
	}
}
