package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : StarGate.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class StarGate extends Building {
	private boolean works;
	private StarGate neighbour;
	
	public boolean getWorks() { return works; }
	public void setWorks(boolean b) { wokrs = b; }
	
	public StarGate getNeighbour() { return neighbour; }
	public void setNeighbour(StarGate sg) { neighbour = sg; }
	
	public StarGate() {
		works = false;
	}
	
	public void onPlace(Asteroid a) {
		if (neighbour == null)
			return;
		
		if (neighbour.getWorks() == false)
			return;
		
		asteroid.addNeighbour(getNeighbourasteroid());
		getNeighbour().addNeighbour(asteroid);
	}
	
	public void destroy() {
		neighbour.setWorks() = false;
		
		getNeighbourAsteroid().removeNeighbour(asteroid);
		asteroid.removeNeighbour(getNeighbourAsteroid());
		
		neighbour.setNeighbour(null);
	}
	
	public Asteroid getNeighbourAsteroid() {
		neighbour.getAsteroid();
	}
}
