package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Uran.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//




public class Uran extends Material {

//Constructors:----------------------------------------------------------------

	/**
	 * Constructor for Uran.
	 */
	Uran(String id){
		super(true, "Uran", false, 0);
		this.id = id;
	}

	/**
	 * Constructor for Uran without parameters.
	 */
	Uran(){
		super(false, "Uran", true , 0);
        this.id = "ura" + String.valueOf(nextId);
        nextId++;
	}
	
//Methods:----------------------------------------------------------------------------

    /**
     * If the Material exposed to the sun 3 times then this function 
     * blow up the asteroid which contains the material..
     */
	public void exposedAndCloseToSun(Asteroid a) {
		super.exposedAndCloseToSun(a);
		if(this.getExposedCounter()>=3) {
			a.explode();
			a.owner.addTurnEvent("material exploded " + this.id );
		}
	}
	
}
