package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Coal.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Coal extends Material {
	
	Coal(){
		super(false, "Coal", false);
	}
}
