package main;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Iron.java
//  @ Date : 17/03/2021
//  @ Author : Barkanyi
//
//




public class Iron extends Material {
	
	/**
	 * Constructor for Iron.
	 */
	Iron(){
		super(false, "Iron", false);
	}
}
