//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Asteroid.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Asteroid extends Planet implements Destroyable, Controllable, Controllable {
	private int rockThickness;
	private Boolean closeToSun;
	private Entity entities;
	private Material material;
	private Asteroid neighbours;
	private Building buildings;
	public void addEntity(Entity e) {
	}
	
	public void removeEntity(Entity e) {
	}
	
	public void explode() {
	}
	
	public void drilling() {
	}
	
	public Material removeMaterial() {
	}
	
	public bool addMaterial(Material m) {
	}
	
	public void removeNeighbour(Asteroid a) {
	}
	
	public void addNeighbour(Asteroid a) {
	}
	
	public void addBuilding(Building b) {
	}
	
	public void removeBuilding(Building b) {
	}
	
	public bool isHollow() {
	}
	
	public void evaporateMaterial() {
	}
	
	public void removeNeighbour() {
	}
}
