//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Building.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public abstract class Building {
	protected Asteroid asteroid;
	protected Game owner;
	public void onPlace(Asteroid a) {
	}
	
	public void destroy() {
	}
}
