//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Controllable.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Controllable implements Robot, Sun, Asteroid {
	public void onTurn() {
	}
}
