//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Game.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Game {
	private Controllable controllables;
	private Settler settlers;
	protected Building owner;
	public void destroyMe(Planet toDestroy) {
	}
	
	public void killMe(Entity toDestroy) {
	}
	
	public void notifyAllAboutSunFlare() {
	}
	
	public void gameWon() {
	}
	
	public void addControllable(Controllable c) {
	}
	
	public void addSettler(Settler s) {
	}
}
