//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Inventory.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Inventory {
	private Material materials;
	private StarGate starGate;
	public Material removeInventory(Material m) {
	}
	
	public StarGate removeStarGate() {
	}
	
	public bool subSet(Inventory i) {
	}
	
	public void addStarGate(StarGate sg) {
	}
	
	public void addInventory(Material m) {
	}
}
