//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Material.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public abstract class Material {
	protected bool isRadio;
	protected String name;
	protected bool canEvaporate;
	public void exposedAndCloseToSun(Asteroid a) {
	}
}
