//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Robot.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Robot extends Entity implements Controllable {
}
