//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Sun.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Sun extends Planet implements Controllable, Controllable {
	public void sunFlare() {
	}
}
