//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Entity.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public abstract class Entity {
	protected Asteroid asteroid;
	protected Game owner;
	
	public Asteroid getAsteroid() {
		return asteroid;
	}

	public void setAsteroid(Asteroid asteroid) {
		this.asteroid = asteroid;
	}

	public Game getOwner() {
		return owner;
	}

	public void setOwner(Game owner) {
		this.owner = owner;
	}

	public void move(Asteroid destination) {
	}
	
	public void drill() {
	}
	
	public void die() {
	}
	
	public void asteroidExploded() {
	}
	
	public void getNotifiedAboutSunflare() {
	}
}
