//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Main.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Main {
	
    public static void main(String[] args) {
    	System.out.println("Hello Skeleton!");
    	
    	/* Test:
    	Game game = new Game();
    	Settler settler = new Settler();
    	
    	game.addSettler(settler);
    	settler.setOwner(game);
    	settler.die();
    	*/
    	
	}
    
    
}
