//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Planet.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public abstract class Planet {
	protected Game owner;
	public void getNotifiedAboutSunflare() {
	}
}
