//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : Settler.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class Settler extends Entity {
	private Inventory inventory;
	private Inventory BASE_RECIPE;
	private Inventory ROBOT_RECIPE;
	private Inventory STARGATE_RECIPE;
	public void mine() {
	}
	
	public void buildStarGate() {
	}
	
	public void buildRobot() {
	}
	
	public void buildBase() {
	}
	
	public void dropMaterial(Material m) {
	}
	
	public void placeStarGate() {
	}
}
