//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Space-Miner
//  @ File Name : StarGate.java
//  @ Date : 17/03/2021
//  @ Author : 
//
//




public class StarGate extends Building {
	private Boolean works;
	private StarGate neighbour;
	public void getNeighbourAsteroid() {
	}
	
	public boolean getWorks() {
		return false;
	}
	
	public Asteroid getAsteroid() {
		return null;
	}
}
